# Generated by Django 6.0.1 on 2026-01-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_favourites',
        ),
        migrations.AddField(
            model_name='user',
            name='user_favourites',
            field=models.ManyToManyField(blank=True, related_name='fav_by_users', to='app.film'),
        ),
    ]
