# Generated by Django 6.0.1 on 2026-01-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_likecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_poster',
            field=models.ImageField(null=True, upload_to='posters'),
        ),
    ]
