# Generated by Django 5.2.6 on 2026-06-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comments_parent_alter_category_id_alter_comments_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likecomment',
            unique_together={('like_comment', 'like_user')},
        ),
    ]
