# Generated by Django 5.2.6 on 2026-06-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_likecomment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_search',
            field=models.CharField(default='', max_length=128),
        ),
    ]
