# Generated by Django 5.2.6 on 2026-06-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_film_film_subcategory_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='film_category',
        ),
    ]
