# Generated by Django 5.2.6 on 2026-06-20 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_film_film_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategory'),
        ),
    ]
