# Generated by Django 5.2.6 on 2026-06-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_film_film_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='age_rating',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='16+', max_length=10),
        ),
        migrations.AddField(
            model_name='film',
            name='budget',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='в минутах', null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='film_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='film',
            name='language',
            field=models.CharField(default='en', max_length=32),
        ),
        migrations.AddField(
            model_name='film',
            name='original_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('released', 'Released'), ('coming', 'Coming Soon')], default='released', max_length=20),
        ),
    ]
