# Generated by Django 5.2.6 on 2026-06-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_film_age_rating_film_budget_film_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
